title: Cristina Saavedra # your name (or website title) here
logo: "images/IMG_20190429_151351-1.png?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Building best-in-class customer experiences,products and teams by transforming data into insights.  
  <head>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>
  <body>
    <i class="material-icons">lightbulb_outline</i>SQL 
    <br><br><i class="material-icons">lightbulb_outline</i>Python
    <i class="material-icons">lightbulb_outline</i>Google Apps Script
    <i class="material-icons">lightbulb_outline</i>Google Data Studio 
    <i class="material-icons">lightbulb_outline</i>Tableau
    <i class="material-icons">lightbulb_outline</i>Arduino
  <br><br>
  </body>
  <br><br>
  <a href="https://www.linkedin.com/in/cristina-saavedra-14b738107/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
